In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [9]:
## list_ is of list, datatype
type(list_)

list

In [10]:
## array_list is of ndarray, datatype which is specific to numpy module
type(array_list)

numpy.ndarray

## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [11]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [12]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:

In [13]:
array_list = np.array(object = list_, dtype = int)

## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [14]:
array_list

array([1, 2, 3, 4, 5])

In [15]:
type(array_list)

numpy.ndarray

### datatype of list_ and array_list will be same. But datatypes of elements of array_list, changed to numpy.int.

In [17]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [20]:
num_array.shape

(2, 3)

In [21]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [25]:
import numpy.matlib as nm

In [26]:
zero_matrix=nm.zeros((3,3))

In [27]:
zero_matrix

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [30]:
identity_matrix=nm.eye(5)

In [31]:
identity_matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])